<h1>Product List by cURL</h1>

<table class='table table-bordered'>
	<thead>
		<th>#</th>
		<th>sku</th>
		<th>Product name</th>
		<th>Action</th>
	</thead>
	<tbody>
		<?php foreach($products as $product): ?>
			<tr>
				<td><?php echo $product->product_id->_ ?></td>
				<td><?php echo $product->sku->_ ?></td>
				<td><?php echo $product->name->_ ?></td>
				<td><a href="product?id=<?= $product->product_id->_;?>">View</a></td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>