<div class="row">
<h1>Magento productList and product methods SOAP client and cURL. Both are accelerated by memcache adapter</h1>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-body">
                <p>API task with the product list and product detail call.</p>
                <p>This request might take some time for the first visit until it will be cached. Don't worry. Usually, it would take about 10-15 seconds.</p>
                <p><a class="btn btn-success pull-right" href="application/magento" target="_blank">SOAP Call</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-body">
                <p><a class="btn btn-success pull-right" href="application/magento/productlistcurl" target="_blank">cURL Call</a></p>
            </div>
        </div>
    </div>

</div>



